### Put request to update a book by ID ###

PUT http://localhost:8080/api/books/book/2
Content-Type: application/json

{
  "title": "What's Become of Waring",
  "pages": 850,
  "publishedDate": "1979-01-14",
  "authorId": 4

}
###