### Put request to update a book by ID ###

PUT http://localhost:8080/api/books/book/266
Content-Type: application/json

{
  "title": "Updated Book Title",
  "author": "Updated Author Name",
  "isbn": "123-4567890123",
  "publishedDate": "2024-06-01"
}
###